### ISSUE TITLE
Can I use this for off the wire (wifi) connection?

### ISSUE THREAD

**Issue by foodornt** [gdzx/audiosource#10]
Title

**Comment by gdzx** [comment]
Hi,

Technically ADB works over the network so you should be able to:

- Enable ADB over the network on your device.
- Start Audio Source on the device.
- `adb connect ip:port`.
- Check that the device is listed in `adb devices`.
- And finally, `./audiosource run`.

But I think you will encounter several issues since this project is not designed at all for this use case:

- Wifi latency & jitter: the buffers are small, late audio packets are skipped, no attempt is made to ensure a smooth playback.
- The device will probably go into sleep.

**Comment by foodornt** [comment]
This is such a comprehensive answer, I really appreciate it.
Thanks a ton!
