### ISSUE TITLE
Windows ?

### ISSUE THREAD

**Issue by Benjiiben53** [gdzx/audiosource#2]
This is a really nice apps but a version for Windows is possible pls ???

Thaks a lot ;)

**Comment by gdzx** [comment]
Hi @Benjiiben53.

Unfortunately, it would be pretty difficult to port this to Windows.

The current Linux implementation relies on a module built into PulseAudio to create a virtual audio source. Doing something similar on Windows would require writing an audio driver and getting it signed by Microsoft.

I didn't find any free and open-source equivalents on Windows. The closest proprietary alternative I found is [WO Mic](https://wolicheng.com/womic/), but I have no idea whether it works as advertised. Because it is closed-source, I cannot guarantee it isn't malicious.

Best regards.

**Comment by abdulhakam** [comment]
Tried via WSL, unsuccessful so far.

**Comment by Benjiiben53** [comment]
> Hi @Benjiiben53.
> 
> Unfortunately, it would be pretty difficult to port this to Windows.
> 
> The current Linux implementation relies on a module built into PulseAudio to create a virtual audio source. Doing something similar on Windows would require writing an audio driver and getting it signed by Microsoft.
> 
> I didn't find any free and open-source equivalents for Windows. The closest proprietary alternative I could find is [WO Mic](https://wolicheng.com/womic/), but I have no idea whether it works as advertised. And because it is closed-source, I cannot guarantee it doesn't do anything malicious.
> 
> Best regards.

Of course, thanks anyway ;)

**Comment by lexybarton** [comment]
I found [pgaskin/pulseaudio-win32](https://github.com/pgaskin/pulseaudio-win32), didn't try it yet though.
