### ISSUE TITLE
Audio skipping

### ISSUE THREAD

**Issue by poopingpenis** [gdzx/audiosource#3]
Audio seems to come and go and the sound is just non-stop skipping, like so
![image](https://user-images.githubusercontent.com/35617595/196310100-b25e1a11-5d5e-4ad5-9096-1d893d674d38.png)

**Comment by poopingpenis** [comment]
Fixed by changing
```
PIPE_SIZE = 4096
BUF_SIZE = 1024 # Must be less than PIPE_BUF = 4096 for atomic writes.
```
in the audiosource script to
```
PIPE_SIZE = 5120
BUF_SIZE = 2048 # Must be less than PIPE_BUF = 4096 for atomic writes.
```

**Comment by gdzx** [comment]
@defaultpage `F_SETPIPE_SZ` is the operation ID when calling [`fcntl(2)`](https://man7.org/linux/man-pages/man2/fcntl.2.html) so it should not be changed.

Increasing `BUF_SIZE` make it so the Python script can write 4096 bytes in a single iteration instead of 4 (if Python is too slow). Increasing `PIPE_SIZE` allows for more room if the consumer and the producer are not called consistently (due to scheduling for instance). The tradeoff here is increased latency.

This issue may appear on a busy / slow system. If you can sustain the stream for some time without any audio skips, then I could make these values configurable directly through the environment. I could also set a higher scheduling priority (but that requires root privileges).

**Comment by gdzx** [comment]
Release [v1.5](https://github.com/gdzx/audiosource/releases/tag/v1.5) contains fixes to the `audiosource` script that may fix these audio skipping issues, if you want to give it a try.
